[package]
name = "tracing-tests"
version = "0.1.0"
authors = ["little-dude <corentinhenry@gmail.com>"]
edition = "2018"

[dependencies]
tokio = {version = "0.2.22", features = ["full"]}
futures = "0.3.5"
